-- ==========================================
-- ADMIN SETUP SCRIPT (SAFE TO RUN REPEATEDLY)
-- ==========================================

-- 1. PROFILES UPDATE (Safe)
-- Add is_admin column if it doesn't exist
do $$ 
begin 
    if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='is_admin') then 
        alter table public.profiles add column is_admin boolean default false; 
    end if; 
end $$;

-- Update specific user to admin
update public.profiles set is_admin = true where email = 'mkorayzengin@gmail.com';

-- Add approval_status if it doesn't exist
do $$ 
begin 
    if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='approval_status') then 
        alter table public.profiles add column approval_status text default 'approved'; 
    end if; 
end $$;

-- Allow Admins to update profiles (for Approval)
drop policy if exists "Admins can update any profile" on public.profiles;
create policy "Admins can update any profile"
on public.profiles
for update
using (
  exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
);

-- Add phone column if it doesn't exist
do $$ 
begin 
    if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='phone') then 
        alter table public.profiles add column phone text; 
    end if; 
end $$;

-- 2. TABLES AND RELATIONS (Safe)

-- CONSTRUCTION REQUESTS foreign key
do $$ 
begin 
    if not exists (select 1 from information_schema.table_constraints where constraint_name='fk_construction_profiles') then 
        alter table public.construction_requests 
        add constraint fk_construction_profiles foreign key (user_id) references public.profiles (id);
    end if; 
end $$;

-- MARKET REQUESTS foreign key
do $$ 
begin 
    if not exists (select 1 from information_schema.table_constraints where constraint_name='fk_market_profiles') then 
        alter table public.market_requests 
        add constraint fk_market_profiles foreign key (user_id) references public.profiles (id);
    end if; 
end $$;


-- 3. TRANSPORT (LOGISTICS) MODULE SETUP

-- Create Transport Requests Table (if not exists)
create table if not exists public.transport_requests (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users,
    from_location text,
    to_location text,
    load_type text,
    weight text,
    vehicle_type text,
    load_details text,
    contact_phone text,
    status text default 'OPEN'
);

-- Add Foreign Key for Transport Requests (Safe)
do $$ 
begin 
    if not exists (select 1 from information_schema.table_constraints where constraint_name='fk_transport_profiles') then 
        alter table public.transport_requests 
        add constraint fk_transport_profiles foreign key (user_id) references public.profiles (id);
    end if; 
end $$;

-- Create Transport Bids Table (if not exists)
create table if not exists public.transport_bids (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    request_id bigint references public.transport_requests(id) on delete cascade,
    provider_id uuid references public.profiles(id),
    price text,
    notes text,
    status text default 'PENDING'
);

-- 4. APP CONFIGURATION (Dynamic Dashboard)

-- Create Module Config Table
create table if not exists public.app_module_config (
    id text primary key, -- 'rental', 'market' etc.
    title text not null,
    subtitle text,
    image_asset_key text, -- Logic mapping: 'cat_rental_v4' -> require(...)
    screen_route text,
    sort_order int default 0,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.app_module_config enable row level security;

-- Policy: Everyone can read
drop policy if exists "Enable read access for all users" on public.app_module_config;
create policy "Enable read access for all users" on public.app_module_config for select using (true);

-- Policy: Only admins can update
drop policy if exists "Enable update for admins" on public.app_module_config;
create policy "Enable update for admins" on public.app_module_config for update using (
  exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
);

-- Seed Data (Insert if not exists)
insert into public.app_module_config (id, title, subtitle, image_asset_key, screen_route, sort_order, is_active)
values 
('rental', 'KİRALAMA', 'İş Makinesi', 'cat_rental_v4', 'RentalStack', 10, true),
('market', 'MARKET', 'Yapı Malzemesi', 'cat_market_v4', 'MarketStack', 20, true),
('renovation', 'TADİLAT', 'Boya & Tamirat', 'cat_renovation_v9', 'Tadilat', 30, true),
('engineering', 'TEKNİK OFİS', 'Mühendis & Mimar', 'cat_engineering_v10', 'Mühendislik', 40, true),
('law', 'HUKUK', 'Yasal Danışmanlık', 'cat_law_v4', 'Hukuk', 50, true),
('logistics', 'NAKLİYE', 'Lojistik Çözüm', 'cat_logistics_v11', 'Nakliye', 60, true),
('urban_transformation', 'KENTSEL DÖNÜŞÜM', 'Devlet Destekli', 'cat_yerindedonusum_v3', 'KentselDonusum', 70, true),
('cost', 'MALİYET', 'Proje Hesabı', 'cat_cost_v5', 'Maliyet', 80, true)
on conflict (id) do nothing;

-- End of Script
