-- 1. PROFILES: Ensure Admin & Status Columns
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS approval_status TEXT DEFAULT 'approved';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS rejection_reason TEXT;

-- Update specific admin (Safe to re-run)
UPDATE public.profiles SET is_admin = TRUE WHERE email = 'mkorayzengin@gmail.com';

-- 2. APP MODULE CONFIG (Dynamic Dashboard)
CREATE TABLE IF NOT EXISTS public.app_module_config (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    image_asset_key TEXT,
    screen_route TEXT,
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.app_module_config ENABLE ROW LEVEL SECURITY;

-- Seed Default Config (Safe Insert)
INSERT INTO public.app_module_config (id, title, subtitle, image_asset_key, screen_route, sort_order, is_active)
VALUES 
('renovation', 'TADİLAT', 'Boya & Tamirat', 'cat_renovation_v9', 'Tadilat', 10, true),
('market', 'MARKET', 'Yapı Malzemesi', 'cat_market_v4', 'MarketStack', 20, true),
('logistics', 'NAKLİYE', 'Lojistik Çözüm', 'cat_logistics_v11', 'Nakliye', 30, true),
('urban_transformation', 'KENTSEL DÖNÜŞÜM', 'Devlet Destekli', 'cat_yerindedonusum_v3', 'KentselDonusum', 40, true),
('engineering', 'TEKNİK OFİS', 'Mühendis & Mimar', 'cat_engineering_v10', 'Mühendislik', 50, true),
('rental', 'KİRALAMA', 'İş Makinesi', 'cat_rental_v4', 'RentalStack', 60, true),
('law', 'HUKUK', 'Yasal Danışmanlık', 'cat_law_v4', 'Hukuk', 70, true),
('cost', 'MALİYET', 'Proje Hesabı', 'cat_cost_v5', 'Maliyet', 80, true)
ON CONFLICT (id) DO NOTHING;

-- 3. TRANSPORT MODULE
CREATE TABLE IF NOT EXISTS public.transport_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users,
    from_location TEXT,
    to_location TEXT,
    load_type TEXT,
    weight TEXT,
    vehicle_type TEXT,
    load_details TEXT,
    contact_phone TEXT,
    status TEXT DEFAULT 'OPEN'
);

CREATE TABLE IF NOT EXISTS public.transport_bids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    request_id BIGINT REFERENCES public.transport_requests(id) ON DELETE CASCADE,
    provider_id UUID REFERENCES public.profiles(id),
    price TEXT,
    notes TEXT,
    status TEXT DEFAULT 'PENDING'
);

ALTER TABLE public.transport_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transport_bids ENABLE ROW LEVEL SECURITY;

-- 4. MARKET MODULE (Ensure Schema)
CREATE TABLE IF NOT EXISTS public.market_requests (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    title TEXT,
    status TEXT DEFAULT 'OPEN',
    location TEXT,
    delivery_time TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.market_request_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    request_id UUID REFERENCES public.market_requests(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    quantity TEXT,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.market_bids (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    request_id UUID REFERENCES public.market_requests(id) ON DELETE CASCADE,
    provider_id UUID REFERENCES public.profiles(id),
    price DECIMAL(12, 2),
    currency TEXT DEFAULT 'TRY',
    notes TEXT,
    status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.market_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_request_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_bids ENABLE ROW LEVEL SECURITY;

-- 5. RLS POLICIES (Consolidated)

-- App Config: Read for all, Write for Admins
DROP POLICY IF EXISTS "Enable read access for all users" ON public.app_module_config;
CREATE POLICY "Enable read access for all users" ON public.app_module_config FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable update for admins" ON public.app_module_config;
CREATE POLICY "Enable update for admins" ON public.app_module_config FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

-- Profiles: Admins can update any profile (Approval Flow)
DROP POLICY IF EXISTS "Admins can update any profile" ON public.profiles;
CREATE POLICY "Admins can update any profile" ON public.profiles FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

-- Transport: Generic policies (Owner can manage, Others can read/bid)
DROP POLICY IF EXISTS "Transport Requests View" ON public.transport_requests;
CREATE POLICY "Transport Requests View" ON public.transport_requests FOR SELECT USING (true);

DROP POLICY IF EXISTS "Transport Requests Insert" ON public.transport_requests;
CREATE POLICY "Transport Requests Insert" ON public.transport_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Transport Requests Delete" ON public.transport_requests;
CREATE POLICY "Transport Requests Delete" ON public.transport_requests FOR DELETE USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true));

-- Market: Generic Policies
DROP POLICY IF EXISTS "Market Requests View" ON public.market_requests;
CREATE POLICY "Market Requests View" ON public.market_requests FOR SELECT USING (true);

DROP POLICY IF EXISTS "Market Requests Insert" ON public.market_requests;
CREATE POLICY "Market Requests Insert" ON public.market_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 6. Construction: Ensure FK
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='fk_construction_profiles') THEN 
        ALTER TABLE public.construction_requests 
        ADD CONSTRAINT fk_construction_profiles FOREIGN KEY (user_id) REFERENCES public.profiles (id);
    END IF; 
END $$;
